### ISSUE TITLE
Change neurons_per_class

### ISSUE THREAD

**Issue by lemonade117** [Shikhargupta/snn-brian-mlp#2]
Hello, first thanks for your explanation in the Readme file. I'v seen your code and try to change the neurons_per_class as 3, then I found it unable to learn from the input images, seems these 3 neurons affect each other,  can you help me explain this problem？

**Comment by Shikhargupta** [comment]
The neurons_per_classs variable defines the output layer of the network. I don't think it is advisable to have more than one output neuron per class.
